version: '3'
services:
  nginx:
    depends_on:
      - watcher
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
  watcher:
    build:
      dockerfile: Dockerfile.dev
      context: ./watcher
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    volumes:
      - /app/node_modules
      - ./watcher:/app
  client:
    depends_on:
      - watcher
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app